services:
  traefik:
    image: traefik:v3.4
    container_name: traefik
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefik/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./certs:/certs

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile

    volumes:
      - ./:/var/www/html

  nginx:
    image: nginx:alpine

    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    depends_on:
      - php

    labels:
      - traefik.enable=true
      - traefik.http.routers.bookingapp.rule=Host(`bookingapp.local`)
      - traefik.http.routers.bookingapp.entrypoints=web,websecure
      - traefik.http.routers.bookingapp.tls=true
      - traefik.http.services.bookingapp.loadbalancer.server.port=80

  database:
    image: mariadb:11.8

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookingapp
      MYSQL_USER: bookingapp
      MYSQL_PASSWORD: bookingapp

    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:5.2
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: https://db.bookingapp.local/
    labels:
      - traefik.enable=true
      - traefik.http.routers.phpmyadmin.rule=Host(`db.bookingapp.local`)
      - traefik.http.routers.phpmyadmin.entrypoints=websecure
      - traefik.http.routers.phpmyadmin.tls=true
      - traefik.http.services.phpmyadmin.loadbalancer.server.port=80

  mailpit:
    image: axllent/mailpit

    labels:
      - traefik.enable=true
      - traefik.http.routers.mailpit.rule=Host(`mail.bookingapp.local`)
      - traefik.http.services.mailpit.loadbalancer.server.port=8025

  redis:
    image: redis:7-alpine

volumes:
  mariadb_data:
