<?php

namespace ContainerCMojkxt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_SensiolabsTypescript_Command_Build_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.sensiolabs_typescript.command.build.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/LazyCommand.php';

        return $container->privates['.sensiolabs_typescript.command.build.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('typescript:build', [], 'Compile TypeScript files to JavaScript', false, #[\Closure(name: 'sensiolabs_typescript.command.build', class: 'Sensiolabs\\TypeScriptBundle\\Command\\TypeScriptBuildCommand')] fn (): \Sensiolabs\TypeScriptBundle\Command\TypeScriptBuildCommand => ($container->privates['sensiolabs_typescript.command.build'] ?? $container->load('getSensiolabsTypescript_Command_BuildService')));
    }
}
