<?php

namespace ContainerCMojkxt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegisterUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Security\RegisterUser' shared autowired service.
     *
     * @return \App\Security\RegisterUser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Security/RegisterUser.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Security\\RegisterUser'])) {
            return $container->privates['App\\Security\\RegisterUser'];
        }

        $instance = new \App\Security\RegisterUser(($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')), $a);

        if (isset($container->privates['App\\Security\\RegisterUser'])) {
            return $container->privates['App\\Security\\RegisterUser'];
        }

        return $container->privates['App\\Security\\RegisterUser'] = $instance;
    }
}
