<?php

namespace ContainerCMojkxt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSensiolabsTypescript_Command_BuildService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sensiolabs_typescript.command.build' shared service.
     *
     * @return \Sensiolabs\TypeScriptBundle\Command\TypeScriptBuildCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/SignalableCommandInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/vendor/sensiolabs/typescript-bundle/src/Command/TypeScriptBuildCommand.php';

        $container->privates['sensiolabs_typescript.command.build'] = $instance = new \Sensiolabs\TypeScriptBundle\Command\TypeScriptBuildCommand(($container->privates['sensiolabs_typescript.builder'] ?? $container->load('getSensiolabsTypescript_BuilderService')));

        $instance->setName('typescript:build');
        $instance->setDescription('Compile TypeScript files to JavaScript');

        return $instance;
    }
}
