<?php

namespace ContainerYCHr1lk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSensiolabsTypescript_PreAssetsCompileListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sensiolabs_typescript.pre_assets_compile_listener' shared service.
     *
     * @return \Sensiolabs\TypeScriptBundle\EventListener\PreAssetsCompileListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sensiolabs/typescript-bundle/src/EventListener/PreAssetsCompileListener.php';

        return $container->privates['sensiolabs_typescript.pre_assets_compile_listener'] = new \Sensiolabs\TypeScriptBundle\EventListener\PreAssetsCompileListener(($container->privates['sensiolabs_typescript.builder'] ?? $container->load('getSensiolabsTypescript_BuilderService')));
    }
}
