<?php

namespace ContainerYCHr1lk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSensiolabsTypescript_BuilderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'sensiolabs_typescript.builder' shared service.
     *
     * @return \Sensiolabs\TypeScriptBundle\TypeScriptBuilder
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/sensiolabs/typescript-bundle/src/TypeScriptBuilder.php';

        return $container->privates['sensiolabs_typescript.builder'] = new \Sensiolabs\TypeScriptBundle\TypeScriptBuilder([(\dirname(__DIR__, 4).'/assets/typescript')], (\dirname(__DIR__, 3).'/typescript'), \dirname(__DIR__, 4), \dirname(__DIR__, 3), NULL, (\dirname(__DIR__, 4).'/.swcrc'), 'v1.3.92');
    }
}
